#!/bin/bash
echo "[1] >>>>>>>>>> 切换到dev分支"
git checkout dev
if [ $? -eq 0 ]; then
    echo "[1] done!"
else
    echo "[1] failed!"
    exit
fi

echo -e "\n[2] >>>>>>>>>> 拉取远程分支代码"
git pull origin dev

if [ $? -eq 0 ]; then
    echo "[2] done!"
else
    echo "[2] failed!"
    exit
fi
